### ISSUE TITLE
call-process errors 126

### ISSUE THREAD

**Issue by bon** [jart/emacs-copilot#2]
I'm getting a return code 126 from the call to call-process. 

The command works from the command line and it's not a problem with finding the model executable. 

The same command works with shell-command but (obviously) puts the output in the wrong place.

Haven't figured out where that error code is coming from. Still investigating...

FWIW Emacs 27.1 on Linux 5.10

**Comment by bon** [comment]
OK the problem appears to be that that `.llamafile` format is unsuitable to be called in a Linux subprocess. If I understand it correctly, this format was designed to be run on a number of different architectures so it may have such limitations.

```
$ file ./wizardcoder-python-34b-v1.0.Q5_K_M.llamafile
./wizardcoder-python-34b-v1.0.Q5_K_M.llamafile: DOS/MBR boot sector; partition 1 : ID=0x7f, active, start-CHS (0x0,0,1), end-CHS (0x3ff,255,63), startsector 0, 4294967295 sectors
```
A workaround is to download the corresponding `.gguf` file and run it with the `llama.cpp` executable. I'll tidy up my solution and post a PR.

**Comment by bon** [comment]
Actually there's an easier way, as [suggested](https://news.ycombinator.com/item?id=38823812) by @jart on hn. You can use one of the [assimilate executables ](https://cosmo.zip/pub/cosmos/bin/assimilate-x86_64.elf) to strip an ELF out of the `.llamafile`

**Comment by lechten** [comment]
This is a wider issue. On Ubuntu 20.04, executing the llamafile on the command line works. With a self-compiled recent Emacs, I get this error: `Doing vfork: Exec format error`

The assimilate-workaround works for me.

**Comment by AdoPi** [comment]
Same error `Doing vfork: Exec format error` on Alpine Linux.

**Comment by pweibert** [comment]
Strange stuff, it used to work perfectly yesterday, but today I'm also getting this "helm-M-x-execute-command: Doing vfork: Exec format error" on Ubuntu 22.04.4 LTS :thinking:. Not quite sure what changed on my system
