### ISSUE TITLE
Consider layering on an LLM-independent API module like llm.el?

### ISSUE THREAD

**Issue by garyo** [jart/emacs-copilot#3]
@ahyatt is working on an LLM layer for Emacs at https://github.com/ahyatt/llm -- just wanted to mention that in case you might want to layer your copilot on top of that for more generality. That way his module can be responsible for authentication, network traffic, etc.

**Comment by jart** [comment]
Thanks, I'll keep that in mind. I've already got my hands full abstracting over all the OSes and architectures. I only care about one LLM right now, which is llama.cpp, and I'm working hard to bring llama.cpp to all the platforms, in a pain-free just-works way.
