### ISSUE TITLE
Emacs reports permission denied on Windows 10

### ISSUE THREAD

**Issue by AnabasisXu** [jart/emacs-copilot#5]
I have download the wizardcoder-python-13b-mainllama.file and placed on ~/bin, and changed the name of the LLAMA model in the script accordingly. 
Then upon calling copilot-complete, Emacs reports 
`let: Searching for program: Permission denied, wizardcoder-python-13b-mainllama.file`

I tried to chmod +x wizardcoder-python-13b-mainllama.file in Shell within Emacs, no error message but the same warning.
Then I tried adding exe to the file extension, and it reports 

`let: Spawning child process: Exec format error`

Not sure what to do with it.

**Comment by jart** [comment]
Windows has a 4GB exe file size limit. See the Gotchas section of the README. You can extract the WizardCoder GGUF weights and modify the elisp to run `llamafile` (download from mozilla ocho releases page) with the `-m wizard.gguf` flag.
