### ISSUE TITLE
client-server mode

### ISSUE THREAD

**Issue by cqvip-jq** [jart/emacs-copilot#6]
I have a power server and weak work-pc. 
Is there any way to deploy the model in power server side
and invoke the code-completion job in work-pc side.

**Comment by g-k** [comment]
If you can SSH from your work PC to your server, a version of this might work https://news.ycombinator.com/item?id=38823609

**Comment by jart** [comment]
Yes please see my hacker news comment about how to configure Emacs Copilot for server mode using SSH. Thanks @g-k!
